### PR TITLE
Change django-compressor==dev to django-compressor==1.2a2 to fix installation

### PR DESCRIPTION
**Pull request by tonyxiao**
Error is: django-compressor has the version 1.2a2, which does not match the requirement django-compressor==dev

### CODE REVIEW

**Comment by rdegges** [comment]
Hi there! Thanks for the pull request. Unfortunately, I'm not able to merge it. I've detailed why in this pull request: https://github.com/rdegges/django-skel/pull/11#issuecomment-6977648

Hope that helps!

**Comment by tonyxiao** [comment]
Thanks a lot for the update. it's really helpful, sorry about the duplicate, didn't realize there is already an issue open for this. One more problem is with celery actually. Was getting error like `cannot import name abbrtask`. Looks like it has to do with 3.0 release. Will look into it further and report back findings.

**Comment by rdegges** [comment]
Hey, no worries. Also: django-skel currently uses the latest pre-3.0 celery release, I haven't gotten around to making all the necessary 3.0 changes yet.

If you can get everything working with 3.0 (using the new aliases instead of the deprecated ones) I'll totally accept the pull request. Last I saw (a few days ago) there were some bugs with celerybeat and Django in the latest celery, so I was waiting it out before investigating :)

**Comment by tonyxiao** [comment]
Finally got the admin page to load on the dev machine. ( Mac OS Lion 10.7.2, python 2.7) 

Had to do the following things.

```
django-admin.py startproject --template=https://github.com/rdegges/django-skel/zipball/master woot

cd woot
mkvirtualenv woot

rm -rf docs README.md
git init
git add .; git commit -m 'First commit using django-skel!'

# Change the line "django-celery==2.5.5" to "django-celery==3.0.1" in reqs/common.txt
# Change the line "django-compressor==dev" to "django-compressor=1.2a2" in reqs/common.txt

pip install django-compressor==dev
pip install -r reqs/dev.txt

python manage.py syncdb

python manage.py migrate

python manage.py runserver
```

Works on dev box so far, yet to try running it on heroku though

**Comment by rdegges** [comment]
I'm having a hard time deciding what to do with this issue. What do you guys think--should I just update the install docs to include changing the compressor version to 1.2a2 for local development?
